[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c032004bbb4768850496140c0f2b774f644d9af7"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[cxx_string.download]]
    sha256 = "58fa0e647a9006e6d8ffa77dd5fef966c22ad4376f57b9d53b6dc15545450b43"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4caff4627c9c3feb0de51a921befe53089f899d"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "b0a84ead34b36a301b84f8c5a25a88beb63247662ea95cafbfa0b5ca63831d57"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea6a8eaccd795a11974e60cd7d5b504700f76bb6"
os = "windows"

    [[cxx_string.download]]
    sha256 = "78a786ffd2c8e76ff5b1c8b239d609f936fd5c718d243c5bb76f0ec2d52ae5e1"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9177cf67a91ed4cb498cbd667a6ed61528a8f87f"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "234c6b79d0f2a59846d94690b6a7b00ad2e6bf17240fc399e0802e209ee61729"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ad163e551a1b0a6841982d985220da8fe1df23a"
os = "windows"

    [[cxx_string.download]]
    sha256 = "a30da999a9822a399d84856a5179efa903cb15e3f7d6c04ee9dd0814ca61d71e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd7337ad4c0e4a03b56277a194300b320d9100f8"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "86ada8d3b8d1396b7cc3d35fcc7392aecd4f75e688f6f9192beb2de1102f8a89"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d43c67460c323139602f5609d5d3849f748b5e56"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "6aa03364c25cef66ad45768ed0c8aeec1d52e33e008bc17e2935e15cf00a33ee"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc92399acb72486a74828f5db92458719c0c15c9"
os = "windows"

    [[cxx_string.download]]
    sha256 = "718fbba167b08a22e8362d485ee14d5a364c745858dc8be63d791c7b6979bcfd"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaba393549412708147482f62b2906bb095cf5e2"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "081e63b141f9c24ab394b2dc03cf2c9dc08dcd71b08ab16a14b2d9bdaae94fa8"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4075f8c8f4d8952aabfca9dcb99082b0a972e4de"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "18cbb9f7c5294b00d865a595cf2adaf4626bf01a33825982de3b9dc15f880ccf"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51ef0b6a391c1ce410285b7f771dd173eff3d0c7"
os = "macos"

    [[cxx_string.download]]
    sha256 = "286dd3101db737acf527f70eb641760715d1730d4850f1e6ae6c209e2a028a39"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1e0681a5d7a73abca25528854b4a90a783665dd"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "fb723301cda6410cf582f6f7d2fdcd3b2e72133e089b129691d994bb6ea738b7"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91fc5978b87a29fe9e359d3f53fc49665dcd7a0f"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "e014172b10bafbf58cdaeb8058f6e4d69ab0d23522803c02f17b9eaeda45be77"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21999c851101755cb0fac7bd16323e29d63e26ad"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "7e2e5ac6c3c841ca85ef009d849f832943b373a9c3563f8f67ba41cb76097b16"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c12fdc2ca5c64e2629a81723e503edc9310f61f8"
os = "windows"

    [[cxx_string.download]]
    sha256 = "f929188de7e8dce6d7f0ab6648fc70bedb91b5d11dccccc235c78756a2fbd03c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10f36b7438b706f2450fbe4ddcbefd35fefe1da5"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "213b770a2a4a264b82ae1332034bbad94dbe4fa959e966970e74278ba5a26432"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1221eaef638ffc3300b840c258fb814cd5dfcefe"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "b48f4c1f5575e4e263a00cc6e112ac5564977e6eeee8096257264b232358625a"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cef7a91c25e6e64430ac6460737539fe0fdd6544"
os = "macos"

    [[cxx_string.download]]
    sha256 = "56c26de8f40376076a1d9c6b936003b7e05ce780369d694bf5a05c98520954d6"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09ca7cb8cd785ab559723c365ea7ed7b4c6623ac"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d5104b4a4bc56d56942306979e24207cdf849827715b6907dcd7a8ef917b42c1"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46db2987438ca9a48f4bf964213720507847ef2e"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "19ae387c8300db61f2884ebe58fa3be05732d1355cd07997873b183eaaaa2e64"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27f6f85e97940cd91a906dea5f7fb1c8e3ff54ab"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "5030d7c76bffe2c7636e7845e7d72bcf1e6edee72cc8edaff3e065114e4154dc"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a71e33bc175e9736546f9ac6668b8d875b7a7f58"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "747cbc14e5fb6607747bdb034be32a9408e46247e9f3222c138512807d65e290"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dec26eb63ee19ad38643cff2c709cc0ab2225836"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "947a05d2b69eb15838c0b8cd53996e2f84f3bbd6ad5fb0fa645f106590833a83"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1cc6ff06c5816136fda2deb1a618d18e105ea9e"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "6b024cc6504f219e87c59b6f2b91304baad1810fd1782fe727ef2afc5240a76c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6337fa87c4059b9fa24798e5c768ccee9e01006"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "a88c11ec2a61a630cacca1275915945916dbe033624b607ca676854897ea5b06"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43812c5658329820fbb8c5dd5734453587bc7115"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "2c395c2b5a33586950b29cbc4a2317a8d2ee7799d727ad3391ea70f7912fc0eb"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffac9baa878974a462a654be020096738ad39ec8"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c1e825b11f7a45bfebcd9e008fa46712d7863964d4a2b0e3eb216e571d9b3a1b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
