[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c032004bbb4768850496140c0f2b774f644d9af7"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[cxx_string.download]]
    sha256 = "58fa0e647a9006e6d8ffa77dd5fef966c22ad4376f57b9d53b6dc15545450b43"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0147332b89301ef76832ce8722fb20c23e898ccf"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "ec1cd741785c42a80aef987e2a74b025fdd6175cde86eb5d99fb54175f313391"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ed6a572250778e6f85bd9cc2231d450badad25a"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c9a5936a1dc8ca43ea6a82cf9590f8933d834ee9fed6417cf07520c77341488f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f327a94b01d3266d14560cc5d0b8792c90cd8c77"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c5cdb21980f81a69ed1d0106de34ba9ac1da3ebd55e1dbbb528c20c4d5600cab"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b535083da59370a35974957de2c2336970fe4abc"
os = "macos"

    [[cxx_string.download]]
    sha256 = "6788e61783992864d830b5dcf85996d30abf35b20c86b77e208da77e12c43928"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1633212f2f91d2ca8863c0fddf64660678e73c9"
os = "windows"

    [[cxx_string.download]]
    sha256 = "bba74037799658ae6f37a4a0537dff21e1a938730c71ccaff6516a8d22d6e192"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5dcb07fe81bfb78c52f2fee0130d570b3bc8b8c7"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "bd2952ff5c1228c984a5f1edb983743a458d8139319ae72d556d382739f96a6c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7732e1c39c6fa645bbe253cf9783a582d5327f4"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "e0beab0b03c7679b60adfa8a68a1a4488188fe9aa1935a0e9a641aece98a6d27"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a6d316e7e5273358c745008150fb67197df99c6"
os = "windows"

    [[cxx_string.download]]
    sha256 = "8881b575b54c83631ef4bd23488c24e6f2a761f254b4fd00f22a09017392ddd5"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8adc9ab852d222875f671727021f70dff2ab405"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "035d47048146eaa8e34927ac5a28ff8b8ed540efca16c7c1bc15b84c266020c0"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e7216642bd720b6b8e3db27eb3bb9b7dec067cd"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c77a6ef968ec8b9b18d7930787079b8a52af77beb0afd0e0e34cff8992a06d95"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32006972565151668fe1a4abd3a6bb6b6650abcf"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "51535583cfdd62e8fdc317eca548f735e23210571e23ecc3cdf944f08142b7e2"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0105e27cd556917de5ace9260cde2eab78fc81fe"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "baa4beb003662418372c7bf982573084c11a66872e96ea9bc8da89c621f9615b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e418885e9b4e72bc86d58f5e1fb4c4ffc6ad872"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "b89d7ff7afa27a8c452b9bcd55a7e02456dbe6a43a6ef443fded2e7c0df04bb4"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8633f5c0352cb4588c3b62b434973cd23c11eb4"
os = "windows"

    [[cxx_string.download]]
    sha256 = "6c08b17c8a4c9abce00bb920b86fb1ed1629b48ab045276947d18b6b9876931c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e635ff5443541834237f78b3861773fa5850b3"
os = "windows"

    [[cxx_string.download]]
    sha256 = "75928f18741fdf9767cbcd4b3b5134ac1cc974cabc824f304c9defa659c94eb6"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d9e68e6604da0b2986668574c05696c16eafc92"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "57314a727afc15d6fcbbbbe4448d51f417552070bd8fc483fc4d275e694417a5"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb285ace51e0520bdb0faefbc94db9dce1ce49ac"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "84cd7f4da42881f32acf3125fdb271cdfaa5a4b3526ede110c87af7d5c7c7280"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80e648ce80a5799268ec7ffee7b27e1baa0af6aa"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "95c93b40f940abb89375adcdca19c4809b002f9d2bec8944ff9344d0a2e068a4"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a4ab076e73112f6813179ad0285edbc51c11c10"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "7215e94f755aa8d0057557f89931f58eecda19f25478a72ba1b78737d2e3601f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c0d1f543369c3b902053d19fe2116e45d3f5e59"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "48c6c0bf85965c0819829225fa4f4e7ae1859842c7490e6d57b1581f14f3f911"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09ee01fe8164bb483b7bf369110eb54ce0aa4136"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "3d80c5216d640b2ac90b23d33e22fef4fba6559a8687430ed41501c2ef9f195f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "120892fca1b27127e580546ea9696b59734b85f9"
os = "macos"

    [[cxx_string.download]]
    sha256 = "7df1c5e93a47f00a7e2ac2eb1b9ffe28808fec624a577126bc2155c026c6561e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2c6f1eaac5d9172ea253bc79e35894e73e68a5c"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "043e00cefcbb19c45adbf9b84ec9c5bb8e9df7ed2b95e8a57b6ba272c5ddc6d2"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a34b91dc5f469185ee3b0d8d66064aca3b81071"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "20270bedf00de6b95886a92fc0ea98a8ebc408e00747b1532cfb6edd8556887d"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1522621423e41cb5d4b4c57b2ec1ad11cff11ee"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "3798e4c268b4429ca540df916814a303ddbecf563fbc9e6ae0663f44fa6a3aac"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03d26546ab82c88bc7d3ddf4cb6cb9c8477e9a18"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "303345c7796f6b782e679756dcff7388673d1b6b437e952e608ba2ca146887b6"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
