[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c032004bbb4768850496140c0f2b774f644d9af7"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[cxx_string.download]]
    sha256 = "58fa0e647a9006e6d8ffa77dd5fef966c22ad4376f57b9d53b6dc15545450b43"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e6cb8b1b27efc0a91be50435d073f1179625f5"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "27b61873d252c0bbae3149139a7a9a81b1f6e2ec0aabc78af4ce5d126a01a15b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "540246b29cbd90fa6c1f292fb74bfe7ac69b9cd8"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "bee0628f669881cbabbb8232e5de52ffa900f4aba6ef9ba212735bb0a58e57cc"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ed9ca06b43d5ec28747cbac1040260cfbe95952"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "34d32939a6777b5dec423882ec77e8e641ab2e6a02bdbb0829716d75aba2a838"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f78f99ecb92a042f903e501ad4f1b9eadf6aa09c"
os = "macos"

    [[cxx_string.download]]
    sha256 = "53eb4c70789796a446254348d076ce9c7f54c225a353e4c430ecb40113852c43"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee8c2786134b31c486839fcf12b4a8848364ced7"
os = "windows"

    [[cxx_string.download]]
    sha256 = "efa95305c289bd46a9dff8028ff33bca905875d05e25edb2481a1d4c69b5ff3a"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17a1b189e721a73b1c3df1e9878750da04911399"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "0a6595b72520e5c00f5f46d05cb61a01465997843376ea11467fa0d65ac7fd77"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b1f20e796749d1dbd0704638bddee1ee6747900"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "236a378118f93e8195ab3cec431c37cec9a38e40a7dbb6c0540843c7c1b3a317"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db34be7fbdc7c391e53ad4d0c27509f38ff172af"
os = "windows"

    [[cxx_string.download]]
    sha256 = "ffbc2a139fc01291f150af5627e27b0baaf895d49338727785e8910baa7f8167"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6021ccf3ee41c2ea70a0f2248c2f3fd86c7dcf4e"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "e7f2fe32efab3140473583929be5ec8658c463bce7a6e83d48372d09579bc5cf"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a8d4a039f55423c4d5b1e6b4f740063d0e8939c"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "13495c728724be88a8b22a0bf1fa264a6f9e06324e4595460de4526442618036"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea0bbcb6a3bf5b8b60d59e9f568856878486775e"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "73a5aea6f6c052279ccd8a10f66c3940c29b2864b4d74c3b860eca39b8466aba"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffa45c1ad44d0983d5f4247beb320e4d87f57a36"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "5393a2c6ac4d6d44332f597d387d90010fff10aae229b955cca400fb073e42d0"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "248815507e44e655d370caf85cfbda9b29b7989c"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "4ff4d28f8ea45515aad44dd9efbad20aea366f28ac7dc40433043da25cba9c9c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c99d20ab119e93a8bcc3525044cac3269674a34"
os = "windows"

    [[cxx_string.download]]
    sha256 = "aee76e3a4c6931f8fc7583ecc308d50415d661c374fd5904556f8eb0ea009854"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "061a74277c60a6b9a959b68a16f1c98c99ed47b0"
os = "windows"

    [[cxx_string.download]]
    sha256 = "7ced3176c1e61df2d119593b0ab040f323b9159189796d3f7df3b64e5b73f95e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e259ee647fa72221ec06571284e2a60275ffcdf"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "4ac10262e7c68da76d031462f61a2bdc324ada8a0cc29bc61a989fc9ba71d4c1"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee645e7e7aba0c7997344ecb30f9e4be63b0c01d"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c1c44d253f4530d77327373a21b6e43629530b56eb4716b78a0c75fadc3ba41f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2be1a96cf0f18e59ce76090c721c5e487a555ecd"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c97eb7d8e98b33c1a4b18ac47b5442da9189ac947f42e474c074d0da111ac34c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a9c76603039cc6916a23a56960065394a64de06"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d09e880dedd79684977462bc982529bd25edb52449c14a1c1ae23b515430f47d"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41cb5ab74461fad94abdb5ef8ca38091829c3e4f"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "fe3b9d0ad2d0d3acfa43dd80d7fb71d9d7891f60abcff24d069dde2476a8fc92"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b7aa26bb78ba33f3f43e47a41b379150307075c"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "66acaad3143544ebbc05eaf83c2f649c6226b7ba3992706b7bd382487867c176"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9642f15717eb6cced094ac47482ff768953ec795"
os = "macos"

    [[cxx_string.download]]
    sha256 = "4be55a04fc831d02af3d2ed680e0939bea9dd7e312473906e6f07dd1b98040a7"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60103c4dafb1190497878953746a483c715ba0f3"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "5ecca1de5eea9f93f240df9ba05fa8f53557320c1b486a7fde636dc009366f01"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "259a47d2c6bdf632bca048c1005a36c89f4b958a"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "4d4e8304a6cc795339dc0591bf552d46c8cd8999d1898cef41024f1f6c6130b1"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76a80f2f399030280c04bfdf686e4761feb5fa90"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "37638dafed9175508cfe58f05d6a5eeb7b086145503265e9876a6788934a5b64"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7edffcb247ef53ddbb3609299e081d8be7dd16d"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "1c1f14f0f5e844a384e19b63f1c19dd429211bcb5f3886d5702b34a39641c8fc"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
