[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c032004bbb4768850496140c0f2b774f644d9af7"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[cxx_string.download]]
    sha256 = "58fa0e647a9006e6d8ffa77dd5fef966c22ad4376f57b9d53b6dc15545450b43"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b40735466a9a0cddf59f2093d6b7a98394dfb8e"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d9b8a1ba60bb07efb11ca2cf015b43b15956f421fd079056d938540ae58da8ad"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6880954b8f4757f0b272d19100a0ac1a27125d0"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "cccee13e94f0bd0d25c09218e4b1d6790343507a32faa67896e77f8a795d2737"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b1c23b8105dae0a7d9863e00ce1542eeb6fcbee"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "2a7a96b60f57a014349faf53f25abe040d38c4c1688c82770642f38c19e3fb94"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15c2d44458412a00ce61ea8f6e1f81856d6106a4"
os = "macos"

    [[cxx_string.download]]
    sha256 = "c9ed7a7a823077da0b2223a0b5fcedc402f54383267a0a68aa8a6be1ac3b1beb"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d096545b299b4a02e422d9c711be24a5242731aa"
os = "windows"

    [[cxx_string.download]]
    sha256 = "d8eff9c9dfc8aa3aaa7aa0b6469a7987c1713eb558659e7adf96bdd47bc83480"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "190bf62f25de2ffcc96971c737251c3cbcfd824d"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "11c6b78bf40fca6a47b8b9456d562ba58b4b467e1af8314335234db9bb26fd26"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b97688d982a0566c769f589684d839aadcc07225"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "5efd5bb35f65ffd1a3e4313ae8e1cefbabcca00d79097a4dabc5331ee2fbf118"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "caad22199d42fc1f889a63f62421353e0ccec288"
os = "windows"

    [[cxx_string.download]]
    sha256 = "d9c0faa6bd13f0035416b6133f96e7f15a4125ff2940e0e08829f724e58a8e3e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45d6c63e1b844cafae38dee0a89b694d5d4d4b08"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "9e564718861f7b65473d0b36e639f4ed7f6660a4e115bea2d1ade39471f85709"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a53ccd46f0de1ed6fd44e65277d3801a3a7cc75f"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "4e91be0e0b2d501872760930938511992435eca7440ebee11531c47e588eb749"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09b57c3a49f2b68225f0393163d3dad0336ae227"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "42f27c089a79537b6fa70208857c96e6fba76edbca43f25919501faf80a33359"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1fa0019741a00c605a3bcf3a4acffc76815ae30"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "8affd3cc4a0aadeb10a1442de548ebf94a174c190a33b5efbeb9b173dbb3c501"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6d021e3bbee98aba2f8c90e2d3541114869b0e3"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "7d0f90fc0f6c28223e7a1b482f7fdeca759d91a95244bdb4b7b9316d70a033cd"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b0963ce264e4e564ba38c0402b94bab6b477a86"
os = "windows"

    [[cxx_string.download]]
    sha256 = "cdb01cb86526261ce0bf972daf0f46798b76f7f36d4a0acf441916fe985daafa"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a577f717682cf44dd19166d581c39e48572397b"
os = "windows"

    [[cxx_string.download]]
    sha256 = "e776bafce0acb53ba33235cd0e42f4ee0a90da96d9d8421d3b47e3224919e38c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "419bd44c0ee1a73e76880cd45694753871928456"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "e519512c5b1c54c4a21b4de4c0c2c6de75f850d5a5fa3ca0f52f2f5d697e5ade"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a180907d7ae406b314d4e2447ba10bd5af62c86"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d217668491e7488fdf25654df698767da8e3a94fb58e15e86561cbd98d25d147"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db12c217eca595f5067d64f07018c63f73f19b7c"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d270afe65a84deef20bf6f05b59f3e69af0db09d1b700154627cbc13a637170e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1151d5502e8084fc550d430d8deb1fbcee1d9b7"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "02293c9111f44aa3353dbd5e64ea56df0a76bf0ea44a76f6b95236c28972575c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3a45be85e4c66be99da6e409cc7622fa464f0cd"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "0b51d48d58e418062f227de00c29b9de3231d04660f3673683cd5977c1591cd7"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cfb34b5f559bb2e63081c7b4a285dad781868ee"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "a843e401952b20b6eb6df67e519ec94f03da7db54c9b46dbd6808c55ea6f338f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef3f07f303caa045f337303079c3edef2ca8cd55"
os = "macos"

    [[cxx_string.download]]
    sha256 = "af8bee135f625f0bda0aeb37ff32b36bef08cbc5edf33dc433debb8ad7a00558"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90462f54f7e561db4c68532bd0ece91d06d2855a"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "a4b03e89226f5127492b5ccf878c4deeaef1406854ebd5e60e109308e8b87be2"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cc35fe2dd2295482563b0219e669f19bad7559f"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "507744bf4044fcf161ab5a6acacaf46506acd1465a0441becb47a8131a1aff88"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abc742fb636f97bab93c5442dce86c4c36a33d66"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "1dbe5906e02b51275b85d085540355a30bd0dfe4ebe1b1b3077a5433e34e1d7c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4a3cbcbc66a21f3ef77f7c2fa5f8ea7598bfcbf"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "dfd0c64c5e08a928d4684ac307e5a8d6edc391302cec1e65ee1009ba3752c604"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
