[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c032004bbb4768850496140c0f2b774f644d9af7"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[cxx_string.download]]
    sha256 = "58fa0e647a9006e6d8ffa77dd5fef966c22ad4376f57b9d53b6dc15545450b43"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90dedf7636d8c1f51bed442267a28035c650b534"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "b10dc9721a1d677e528c86f984e927f6796cdd1d1ec2b9e27bafc273f26a72c2"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b3cd1ba9e4c309e50b2113ba18e132f3847d221"
os = "windows"

    [[cxx_string.download]]
    sha256 = "8a405e763dde5487d1635624de249e99710e253049635fd12118629667bdb03a"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d2b3b09b6e6aa63859a7e52e922bd17809d4173"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "376e8afcf9a823c1015072a96fa978680cc69e27320c308492a4d9fbd6407af0"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4dd18c8ed2bf667762431e778194085967db6971"
os = "windows"

    [[cxx_string.download]]
    sha256 = "d170e87ec42063195003aa14045e73102dbd53e09c4c6f81551182df6ec92910"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd64429f9e5db5ef506c4ebed0783e925574c580"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "fa3bd6eb1b11cf6bffb07d02551e105a15e35b84375a51180dfe14809a81f444"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "253b6cf664e40a65d4b3101b35d84c2188bd71b0"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "923d8529b66490d3e57983a78c550fb0615b2762d538d0dd7b8fc29987611b49"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "107c61a69f4d93905a816c83e76902d4da1858dc"
os = "windows"

    [[cxx_string.download]]
    sha256 = "e2afb59323d43d472263e134e6d38fdd486b10d0df38e0aeee4c0d59e49e5340"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80270684c0211f4358325e9e85cfaf3057cbdfe9"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "169a65e011872d8a05bd6f6b6485b31ba7907292ad101ca07b68aa6b6f45030c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcffc6ff8551e8f4763e038575d30eb57acab1a2"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "128128db75cb7ae66fff06143ca9bc79b7d383e93170523df3b18eca874509b6"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1206b6f98b213f292c95cd118b9ec81b6f129415"
os = "macos"

    [[cxx_string.download]]
    sha256 = "9d5a69ae1dcb7e09ed5e22f23f415b621821245f933681039480a41ff8d4ca37"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f852258e13541e1d0950a4bfc786606e5c3a138"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "75eefd0801468b21a6636c06b7581ab685cbf1686f22d583684ce01132fb13c8"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2d5b2701c02e3d2d3ccf0d8e1db844120792a8a"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "5d9189829e5be69a3688632f38efb2a59d3f8328f147c88be3dcd21c3ca5338f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac640862863f4a50fd45737c6531ebcc16cbb9b7"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "186d683471876a4ef47cf0d6b4edbba61b04071b5e402bb3b809ac7bb9d61972"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1ba4facf305a5bc7a7f4ef90e0b422f6a16e0bb"
os = "windows"

    [[cxx_string.download]]
    sha256 = "ae5842719aed07accbb5f9576a703dc9ba8eee7504847e521710d850651c9b69"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b018a967faa6031727714992201e16fa70361bae"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "cd133a80b8de131d22fbdee103b87583f804066ba7f5e5e65371ec7e009901ed"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d24866df2bb57e65842f053702bdc3dc40932009"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "85ff220b063a70831caa3db177ab0464a314a3a102bcf6affac8cc9f86c0f098"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f067e8a91483a1017ef4e69f32c07e7cd9adf4be"
os = "macos"

    [[cxx_string.download]]
    sha256 = "f65f1499f50fa063eb90e0f70535146d775955d95419fb5f2bce97d9003317af"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b72c52a7f59353e74810efa2a7bd8e2abce6daa3"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d4a2023ab255c24e8cfec7fdd8a0407a950d88ac6abf13576b4586cb5b323e91"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e45d8ddc20fb76b5a169c3085378d1473fd846d"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "ff10306321935cc28e447f1cdcaf84cf1954174442cfc90bb0d8c11e9ffa12ed"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d499c8cb536189221f45ee85499c0686cae4994a"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "ce640218f6f1eca8178500ab321597acc777346dd5d7eaacb46ede4d649b12db"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cce3e6d60a519632f1c18bb45e86facec68d68d"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "9b44b7e8ba88c9311e47b0f8b99708a39163dd6ea8390dc1c926872d602d224c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "101c212eb8db7e6a5c44cc44a09bda72258a870d"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "608d1669ad0796f3aa5c3605a61895391b72f8940bf60a12e47d7e2827f7578b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d1c4d5bf5ae0c2662a30ebf3062f7dc577081a3"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "cce5e7699723671844f4ed2a7531cf166cb5ab733c14d80e887a52a483148bbc"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f04c75410830611a01c56d28b65e287e4c1c64ff"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d2ebd20464ac9ef4143e4063f528c681bb28d85ab0f2a1724f1a74e5158dbe47"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83f7baf41d5a4cca749dbda3b80c93765a7c803d"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "837e858ad53e3f02537e686bd329f515415e06a9c4c38fcc5786322d25017d2c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1db2b2794835709d067b2130595ad7249b3d3aff"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "b8ce66ebd5b7e42e2ca8d65e3fceeaf9fae78976d3b8403bb04fa32259d7e705"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
