[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b22b63ef4bd0561db0fcb9c0e7841b023f2867b7"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c08ee171a563bff6f6770e219b28c3644bd56915a9f44e4557a3e92a99445f3f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c241594f2132a4f16f5f94151078a5f173a64dea"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d0b309ff902acd1125062c7403a4abbf1e17e10e4ded7474fb2f39289889a4b7"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "218f202d61e96c72b34121bfffaadb514dcaba7f"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "4a60f9e3f0f36bd5503d49cf6346f53c9597488f8bc70f023b818e2c52389ccd"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ff92707a377f4f831c863bdee7e2246e2d0fc48"
os = "macos"

    [[cxx_string.download]]
    sha256 = "8a8b535d8ea9fae6821503172a9611dcb13ae75ec68f72fe436acad460b4f960"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d3a142bbf5b66a36513144fea284ec29767338a"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "aadbb3ed65b2f67f9bdb6bb791fe2b33caf9c0f2ce957a6524fc529c4795d063"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c2d24388c055263bd21592fb5aefccb5b73fba1"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "65fb2b63a75993c95604794b54bbf029bb806bd0beb47e080657567586f0718e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fba2f244bd4cfa3f9e6cf68c76e9f23a3b7dc138"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "5cc77ca71e84fc6346261cf63178eaeb75aa04700b12fab2ef0d0e6b1ae7caee"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d099a654c0029437a95029114d26a8a5a0dfca0c"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "31d21e40d65da6976d1485f4b5ec48e01cbc00c7d2bd9ea61c64f44f48593e65"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65f77693f8fc522bc52e826ba53291440587e51c"
os = "windows"

    [[cxx_string.download]]
    sha256 = "8d3a3d457c006e146d2c2c65683e72b09512b17846bc65629c4ccc5c2cb2d0dd"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf333e1bbfa9d2f1aab8a8e1cb53fcc42bf4734b"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "05b599e3b1eb7076a283d6b81b289818edf0bf50fc04fc6880d9aad746ea19d8"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ede416c2c3039c94a505b42472f7ff78c49b9f37"
os = "windows"

    [[cxx_string.download]]
    sha256 = "31f7e3c48a7dd9d0f98b0f88304e7f07c258b110ab8ad3d13c5843acddb00acc"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44ba74fa25516f728671c5962336a843742d091e"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "1b551fd2d8bf8445f7c9d029e72863cc9f2f045eb2ff0878f79cdd8d51d5ee74"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65a251c6dafbe02ef34e845e12cd1be5e7cef03b"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c008fd1ebca6ee491c4ffa4ff48ed544a5297234b3b05510690b4608e1cdfe56"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8d19e995ebc9585740cfc9b2ee014a163e80215"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "dc17828f7dd2529f466cc679126242e7b074512bcf0070bfd09713b5fb7e584b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a7b4b2982c6c75e0bc74de5de22a5f971e69220"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "6bd36373beb8623ddbad23f74556c429ebaac5f3e3c0fc78066c952585a22bfd"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5977b499749a7ec755a3cfac2635c6894b4a5272"
os = "macos"

    [[cxx_string.download]]
    sha256 = "c6b0305c408b9273744fea633750f6e3b1eafd61b26990c543213cc37d258d81"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "391c9e76d0aa2e8ad5e6d9afd1b726b411de0825"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "0a70dfdefc0b77dc3c425f9d9ee64b9b0dc906a777733104b5541b30689c203b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "075a1e35064dea958ca0b8673c2e88789b37d967"
os = "windows"

    [[cxx_string.download]]
    sha256 = "2a247cda936b63e018573ad617eb219ccad9595c9c9433442dd9b7dfe41ae7d8"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b6106e4cab357290633f1bbe298aa4be56a4a18"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c566fe22881913d0741a71119cfd6910e20873aac12c5fb99542237ec9d803e7"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a5d5d7edac9b7f467f769756342d31e7b086300"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "69cc45f690de7533948cfad29dbd8f356b8e95b4ffed1b719164da247eb2b032"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0512bfdba38a1c8a005c4e88b2989be37bc276fb"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "231d59fa6603e434b6b2c293fe9a8f33b9af5d6f819f0d329696b32b9546843b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fa9e4b3ccc0d7fca6aba3b6e2b52c15109003cf"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "10e1faa3e3a5e0790f6d3336c6d555fad210476ee7f8004b8279dcaeb09dfd06"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c79b704a76ef680532290871ca1d6ff62644e3de"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "e7c2f7f871cc8294cf6f7ae209768bd46ecd5816806926b70c9f93cddc0efc75"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab774e2445bbfe0685ba3bbc7ef2f3a43859e2c1"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "b2cf6cde2dc395be726b7a913174126224d73cbfdc56b02b0ff19534124be8b4"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b86f94563b49d5f73197e11049d24903ac90835c"
os = "windows"

    [[cxx_string.download]]
    sha256 = "adbfba73a6488f0c839ade6c654fed86554acde948292fea7f2d5ac1e5f5c242"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c25caa3fb884a2bd6fb8eb707f4f4ac6fab038f"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "0324300c5a8113b666cdca9a036749e6e595d0e36b3886bad27fe183c66be43b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b702fdaf9f2e64e0be30e074cc588c5c23fbdcc"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[cxx_string.download]]
    sha256 = "8445939dfa75fc7ebc8c40ecb47cd162a1372b06fa72b6dd4cc263d43040df0c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
