[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b24f6f223495a947144d183a2fde03686ea13fde"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "d9ca63915ce4dd6efe0f0834764bebc570da949e92b6c4888c2e89a1192fa9b4"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28fa37a555ecad4e34d03220625d20f5facf98aa"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "49fd18e143b4fe0afe2202a90830d055a919dfc91fa69ecbd8f3dd8865f57ba4"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bcfa4a73ee9a6d3879dbf90f410e7f6b3cac99d"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "e77611438003400ebdb4eb7dd6ec113fd6cdb0aacc870ce9e2b65bc23a006786"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4275ede3ce92d933a5db970bceed01b6d865855c"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "9cce2deb729b2e4d27f57a43195d96fa7c8aafa1dab6bfeb08922e346f553bd0"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4375b67dc0b4d9ef438b0ea7739d9e37a42cde0"
os = "windows"

    [[cxx_string.download]]
    sha256 = "b6a0314bc558533d0204cefb2a789a1fc267ac68892c2d8bf06590ec1dd989c4"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4136aaca8d71cde6aba7646095084b1f6308af23"
os = "windows"

    [[cxx_string.download]]
    sha256 = "8fd307a5a0c512aa79357a5e0c0d9c25b74d1b2810c2cc300dc8474c816ad1b2"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e3bf7564361b462e369dfbfc72e562e02f6163a"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "6eb51f75d93f6ba6e42fd22acd6ba7b30a28d1ad7f872e4f670ea985180805cb"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "448fb1c31856bcece6876f1730dbb1d13b5674f4"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "7c5a636112b4ab1ff1d1370f6051ac262682417f9d3bf5ac370452b9894c037a"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "053f1cccca63a857c13f1b2bfad30b189ad08aab"
os = "windows"

    [[cxx_string.download]]
    sha256 = "0641d413bf864624d34d4791eaebbd5964ae1e34c8c6d3253084bf0e79f8df12"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c16fbe51f2fe3c3e9ba2518909808e68c0b4a8f4"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "2e9f0f20d38cabd56dba9ead1afc39550478d115bff5b1df79fde74f8aae380e"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f068b996372974148a721ee8c1b1dae93e6eb68a"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c11e52606dd57c450c48a51530fead6e171e21b0b2105780a1718da4b41b1341"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "219a44044fd2df2ab742b76a68db310ce1f42b5d"
os = "macos"

    [[cxx_string.download]]
    sha256 = "470fb118f4926d4530eed73d476022bd7a4a01ae82a22e3b9bf477cc44dc58eb"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6abbe2303a6973f396b2c83b3081ecf38432e5b5"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "672dff13b50eb87682f29923929b86a7e2a45edeb7647fdd2a47adf7709bd5a3"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "748311f216070501072430bda10aa81102f58ad6"
os = "freebsd"

    [[cxx_string.download]]
    sha256 = "2ce3359d45324fecc15b363151736b12f7e7f8c8687ab3e91badbc1353d83e0c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb00d4d5b372677c2e9a2fd9e983edbee370502e"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c273e0deda63f1628190fa6155ad5d3e643e7594f320f214440bd977854fa653"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "328fa03efcb55a6fcce90637ce1f73a8a221e754"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "5cb91001e194ec8a4b1d61301de061e8efe4a141d8a4c40105f5131f7a8fd503"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cac52085ee7012a7653464369ba357ee17df351"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "78efed6edfd9afbfaa3dfcbebedb5baba82b8150b35fb426bc1cb5b390f5eaa9"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-musleabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e02110c1ad26ef0ae70f8274fb9386aeab25d28e"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "f19c04f21da0dae909114509b352979c777b28fd8abb59bab1c5d342b048f34b"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdc17bbdd7cfaf5fa2a91c9c00ac2328dea6bd45"
os = "windows"

    [[cxx_string.download]]
    sha256 = "aaa0e8b134be682a542cba07efa67d956e74a9c167302c4359340c521af36953"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-w64-mingw32-cxx11.tar.gz"
[[cxx_string]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d0742277cc83930f9fc9affe957101162eb8ffa"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "83879056c754f33433b39a67e7dcfd4be6f3e808c4861a2dadb59d47f7bc0410"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.arm-linux-gnueabihf-cxx11.tar.gz"
[[cxx_string]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "965b9ffb45a7e148b577d5944cd567afe9fd76c7"
libc = "glibc"
os = "linux"

    [[cxx_string.download]]
    sha256 = "86287bbe21a3a82a87f1ba40f55ddfe35c167d1bff795d2bf04360e85874bdac"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[cxx_string]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a6d9ba3a0ac0152e576d1fbfdbe8e5a6202895a"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "4d46acd80c91c22083205e52d91a94d587f865737044a3252bab0610e322602c"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.i686-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb7a94bdd4f7d2db8a931b661ffa975097e33b1b"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c798f149d89a26e33d4c95720e71d8c1f64265422d0b82cd1810af0c3f263365"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f09bcb9ce79f759746a2c3dafd5fad31032433dc"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "c0e3dc7a76aae606d7bb86b02959909d74f2cbb928e060ffdf7331b9976e68b3"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.aarch64-linux-musl-cxx03.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2accafd45fb2c931b89c9c5e8c83234fc4d5add"
libc = "musl"
os = "linux"

    [[cxx_string.download]]
    sha256 = "55cfea864a32a18598e70f9b1b1c9484e22998732b5eae640de4f756f4908e28"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-linux-musl-cxx11.tar.gz"
[[cxx_string]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22561c90b0f2c8eafa6054491609d62a0fe4c6d3"
os = "macos"

    [[cxx_string.download]]
    sha256 = "2eb49d04aca484c40a1f31d731a90486edcc5e598b1824583d82bc5d77773a6f"
    url = "https://github.com/JuliaBinaryWrappers/cxx_string_jll.jl/releases/download/cxx_string+v1.2.4+0/cxx_string.v1.2.4.x86_64-apple-darwin14-cxx03.tar.gz"
